<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>txt</string>
		<string>markdown</string>
		<string>mdown</string>
		<string>markdn</string>
		<string>md</string>
	</array>
	<key>name</key>
	<string>Wiki</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>[A-Z][a-z]+([A-Z][a-z]*)+</string>
			<key>name</key>
			<string>markup.other.pagename.camelcase</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.other.pagename.delimited</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\[\[(.+)\]\]</string>
		</dict>
	</array>
	<key>injectionSelector</key>
	<string>L: text</string>
	<key>scopeName</key>
	<string>text.html.markdown.wiki</string>
	<key>uuid</key>
	<string>F861513D-753A-4D79-8679-4EE3D034F5A8</string>
</dict>
</plist>
